name: Publish

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ">=8.10"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Add Svelte Check annotator
        uses: prgm-dev/svelte-check-pr-annotator@main

      - name: Check
        run: pnpm check --output machine

      - name: Type Converage
        run: pnpm type-coverage

      - name: Run ESLint
        run: pnpm lint:ci --output-file .eslint_report.json --format json
        continue-on-error: true

      - name: Annotate ESLint Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: ".eslint_report.json"

      - name: Run Prettier
        run: pnpm prettier:ci

      - name: Build
        run: pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: "build/"

  Publish:
    if: ${{ (github.event_name != 'pull_request') && (github.ref_name == 'main') }}
    needs: Build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
